---
name: tests
on:
  pull_request:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # weekly
jobs:
  tests:
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Setup
        run: |
          npm install
      - name: Test
        run: |
          npm run-script test
